[package]
name = "app"
edition = "2021"

[dependencies]
tauri = { version = "1.0", features = ["api"] }
sqlite = "0.28"
shell = "0.8"
chrono = "0.4"
serde = { version = "1.0", features = ["derive"] }
